title: 'Contact Form Configuration'
fields:
  -
    handle: contact_info_title
    field:
      type: text
      display: 'Contact Info Title'
      instructions: 'Title for the contact information column'
      default: 'Visit Us'
  -
    handle: form_title
    field:
      type: text
      display: 'Form Title'
      instructions: 'Title for the contact form column'
      default: 'Send us a Message'
  -
    handle: show_contact_info
    field:
      type: checkboxes
      display: 'Contact Information to Display'
      instructions: 'Select which contact details to show'
      default:
        - address
        - phone
        - email
        - hours
        - reservation_button
      options:
        address: Address
        phone: Phone
        email: Email
        hours: 'Opening Hours'
        reservation_button: 'Reservation Button'
  -
    handle: form_fields
    field:
      type: checkboxes
      display: 'Form Fields'
      instructions: 'Select which fields to include in the contact form'
      default:
        - name
        - email
        - phone
        - date_time
        - party_size
        - message
      options:
        name: Name
        email: Email
        phone: Phone
        date_time: 'Date & Time'
        party_size: 'Party Size'
        message: Message